package Javalette.Absyn; // Java Package generated by the BNF Converter.

public abstract class Blk implements java.io.Serializable {
  public abstract <R,A> R accept(Blk.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Javalette.Absyn.Block p, A arg);

  }

}
