package Javalette.Absyn; // Java Package generated by the BNF Converter.

public class Block extends Blk {
  public final ListStmt liststmt_;
  public Block(ListStmt p1) { liststmt_ = p1; }

  public <R,A> R accept(Javalette.Absyn.Blk.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Javalette.Absyn.Block) {
      Javalette.Absyn.Block x = (Javalette.Absyn.Block)o;
      return this.liststmt_.equals(x.liststmt_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststmt_.hashCode();
  }


}
