package Javalette.Absyn; // Java Package generated by the BNF Converter.

public class Decl extends Stmt {
  public final Type type_;
  public final ListItem listitem_;
  public Decl(Type p1, ListItem p2) { type_ = p1; listitem_ = p2; }

  public <R,A> R accept(Javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Javalette.Absyn.Decl) {
      Javalette.Absyn.Decl x = (Javalette.Absyn.Decl)o;
      return this.type_.equals(x.type_) && this.listitem_.equals(x.listitem_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.listitem_.hashCode();
  }


}
