package Javalette.Absyn; // Java Package generated by the BNF Converter.

public class For extends Stmt {
  public final Type type_;
  public final String ident_;
  public final Expr expr_;
  public final Stmt stmt_;
  public For(Type p1, String p2, Expr p3, Stmt p4) { type_ = p1; ident_ = p2; expr_ = p3; stmt_ = p4; }

  public <R,A> R accept(Javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Javalette.Absyn.For) {
      Javalette.Absyn.For x = (Javalette.Absyn.For)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_) && this.stmt_.equals(x.stmt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.type_.hashCode())+this.ident_.hashCode())+this.expr_.hashCode())+this.stmt_.hashCode();
  }


}
