package Javalette.Absyn; // Java Package generated by the BNF Converter.

public class Program extends Prog {
  public final ListTopDef listtopdef_;
  public Program(ListTopDef p1) { listtopdef_ = p1; }

  public <R,A> R accept(Javalette.Absyn.Prog.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Javalette.Absyn.Program) {
      Javalette.Absyn.Program x = (Javalette.Absyn.Program)o;
      return this.listtopdef_.equals(x.listtopdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtopdef_.hashCode();
  }


}
