package Javalette.Absyn; // Java Package generated by the BNF Converter.

public class SExp extends Stmt {
  public final Expr expr_;
  public SExp(Expr p1) { expr_ = p1; }

  public <R,A> R accept(Javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Javalette.Absyn.SExp) {
      Javalette.Absyn.SExp x = (Javalette.Absyn.SExp)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
