package Javalette.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Javalette.Absyn.Empty p, A arg);
    public R visit(Javalette.Absyn.BStmt p, A arg);
    public R visit(Javalette.Absyn.Decl p, A arg);
    public R visit(Javalette.Absyn.Ass p, A arg);
    public R visit(Javalette.Absyn.AssArray p, A arg);
    public R visit(Javalette.Absyn.Incr p, A arg);
    public R visit(Javalette.Absyn.Decr p, A arg);
    public R visit(Javalette.Absyn.Ret p, A arg);
    public R visit(Javalette.Absyn.VRet p, A arg);
    public R visit(Javalette.Absyn.Cond p, A arg);
    public R visit(Javalette.Absyn.CondElse p, A arg);
    public R visit(Javalette.Absyn.While p, A arg);
    public R visit(Javalette.Absyn.For p, A arg);
    public R visit(Javalette.Absyn.SExp p, A arg);

  }

}
