package Javalette.Absyn; // Java Package generated by the BNF Converter.

public abstract class TopDef implements java.io.Serializable {
  public abstract <R,A> R accept(TopDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Javalette.Absyn.FnDef p, A arg);

  }

}
