package Javalette.Absyn; // Java Package generated by the BNF Converter.

public class VRet extends Stmt {
  public VRet() { }

  public <R,A> R accept(Javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Javalette.Absyn.VRet) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
